kind: Pod
apiVersion: v1
metadata:
  annotations:
    openshift.io/scc: anyuid
  name: orig-ldap
  namespace: confluent2
  labels:
    app: ldap
spec:
  restartPolicy: Always
  serviceAccountName: default
  imagePullSecrets:
    - name: default-dockercfg-7wnxq
  priority: 0
  subdomain: ldap
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: 10.72.245.90
  securityContext:
    seLinuxOptions:
      level: 's0:c26,c15'
  containers:
    - resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "1025Mi"
          cpu: "500m"
      terminationMessagePath: /dev/termination-log
      name: ldap
      env:
        - name: LDAP_TLS_VERIFY_CLIENT
          value: try
        - name: LDAP_TLS_CRT_FILENAME
          value: tls.crt
        - name: LDAP_TLS_KEY_FILENAME
          value: tls.key
        - name: LDAP_TLS_CA_CRT_FILENAME
          value: ca.crt
        - name: LDAP_TLS
          value: 'true'
        - name: LDAP_ADMIN_PASSWORD
          value: confluentrox
        - name: LDAP_CONFIG_PASSWORD
          value: confluentconfigrox
        - name: LDAP_DOMAIN
          value: test.com
        - name: LDAP_ORGANISATION
          value: Test Inc.
        - name: LDAP_READONLY_USER
          value: 'true'
        - name: LDAP_READONLY_USER_PASSWORD
          value: Developer!
        - name: LDAP_READONLY_USER_USERNAME
          value: mds

      securityContext:
        capabilities:
          drop:
            - KILL
            - MKNOD
            - SETGID
            - SETUID     
      ports:
        - name: ldap
          containerPort: 389
          protocol: TCP
        - name: ldaps
          containerPort: 636
          protocol: TCP
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: sslcerts-volume
          mountPath: /container/service/slapd/assets/certs
        - name: ldap-data
          mountPath: /var/lib/ldap
        - name: ldap-config
          mountPath: /etc/ldap/slapd.d
        - name: customldif
          mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
        - name: default-token-llvzr
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: 'osixia/openldap:1.3.0'
      args:
        - '--copy-service'
        - '--loglevel=trace'
  hostname: ldap-0
  serviceAccount: default
  volumes:
    - name: ldap-data
      persistentVolumeClaim:
        claimName: ldap-data-ldap-1
    - name: ldap-config
      persistentVolumeClaim:
        claimName: ldap-config-ldap-1
    - name: sslcerts-volume
      secret:
        secretName: ldap-sslcerts
        defaultMode: 420
    - name: customldif
      configMap:
        name: ldap-ldifs
        defaultMode: 420
    - name: default-token-llvzr
      secret:
        secretName: default-token-llvzr
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
