kind: Pod
apiVersion: v1
metadata:
  name: ben-ldap
  namespace: confluent2
  labels:
    app: ldap
spec:
  restartPolicy: Always
  imagePullSecrets:
    - name: default-dockercfg-7wnxq
  nodeName: 10.72.245.90
  containers:
    - resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "1025Mi"
          cpu: "500m"
      terminationMessagePath: /dev/termination-log
      name: ldap
      env:
        - name: LDAP_TLS_VERIFY_CLIENT
          value: try
        - name: LDAP_TLS_CRT_FILENAME
          value: tls.crt
        - name: LDAP_TLS_KEY_FILENAME
          value: tls.key
        - name: LDAP_TLS_CA_CRT_FILENAME
          value: ca.crt
        - name: LDAP_TLS
          value: 'true'
        - name: LDAP_ADMIN_PASSWORD
          value: confluentrox
        - name: LDAP_CONFIG_PASSWORD
          value: confluentconfigrox
        - name: LDAP_DOMAIN
          value: test.com
        - name: LDAP_ORGANISATION
          value: Test Inc.
        - name: LDAP_READONLY_USER
          value: 'true'
        - name: LDAP_READONLY_USER_PASSWORD
          value: Developer!
        - name: LDAP_READONLY_USER_USERNAME
          value: mds
      volumeMounts:
        - name: sslcerts-volume
          mountPath: /container/service/slapd/assets/certs
        - name: ldap-data
          mountPath: /var/lib/ldap
        - name: ldap-config
          mountPath: /etc/ldap/slapd.d
        - name: customldif
          mountPath: /container/service/slapd/assets/config/bootstrap/ldif/custom
        - name: default-token-llvzr
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      ports:
        - name: ldap
          containerPort: 389
          protocol: TCP
        - name: ldaps
          containerPort: 636
          protocol: TCP
      imagePullPolicy: IfNotPresent
      image: 'osixia/openldap:1.3.0'
      args:
        - '--copy-service'
        - '--loglevel=trace'
  volumes:
    - name: ldap-data
      persistentVolumeClaim:
        claimName: ldap-data-ldap-0
    - name: ldap-config
      persistentVolumeClaim:
        claimName: ldap-config-ldap-0
    - name: sslcerts-volume
      secret:
        secretName: ldap-sslcerts
        defaultMode: 420
    - name: customldif
      configMap:
        name: ldap-ldifs
        defaultMode: 420
    - name: default-token-llvzr
      secret:
        secretName: default-token-llvzr
        defaultMode: 420